/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingprojects;

import javax.swing.JOptionPane;

/**
 *
 * @author Bipin
 */
public class CalculatorView extends javax.swing.JFrame {
    double num1,num2;
    double result;
    String operator;
    
    

    /**
     * Creates new form Calculator
     */
    public CalculatorView() {
        initComponents();
        RadioButtonON.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        DisplayText = new javax.swing.JTextField();
        ButtonAllClear = new javax.swing.JButton();
        ButtonPercentage = new javax.swing.JButton();
        ButtonOneByX = new javax.swing.JButton();
        ButtonSquareRoot = new javax.swing.JButton();
        ButtonCubeRoot = new javax.swing.JButton();
        ButtonFactorial = new javax.swing.JButton();
        ButtonOff = new javax.swing.JButton();
        ButtonDivide = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        ButtoneEulerNumber = new javax.swing.JButton();
        ButtonSin = new javax.swing.JButton();
        ButtonInverse = new javax.swing.JButton();
        ButtonPI = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        ButtonMultiply = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        ButtonLog = new javax.swing.JButton();
        ButtonCos = new javax.swing.JButton();
        ButtonAntilog = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        ButtonTan = new javax.swing.JButton();
        ButtonSquare = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        ButtonMinus = new javax.swing.JButton();
        Button10powerX = new javax.swing.JButton();
        ButtonPower = new javax.swing.JButton();
        ButtonPlus = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        ButtonEqualsTo = new javax.swing.JButton();
        ButtonBackSpace = new javax.swing.JButton();
        ButtonPoint = new javax.swing.JButton();
        RadioButtonON = new javax.swing.JRadioButton();
        RadioButtonOFF = new javax.swing.JRadioButton();
        Label = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        DisplayText.setBackground(new java.awt.Color(204, 204, 255));
        DisplayText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        DisplayText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        DisplayText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayTextActionPerformed(evt);
            }
        });

        ButtonAllClear.setBackground(new java.awt.Color(204, 0, 0));
        ButtonAllClear.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAllClear.setText("AC");
        ButtonAllClear.setToolTipText("");
        ButtonAllClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAllClearActionPerformed(evt);
            }
        });

        ButtonPercentage.setBackground(new java.awt.Color(153, 153, 153));
        ButtonPercentage.setText("%");
        ButtonPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPercentageActionPerformed(evt);
            }
        });

        ButtonOneByX.setBackground(new java.awt.Color(153, 153, 153));
        ButtonOneByX.setText("1/x");
        ButtonOneByX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOneByXActionPerformed(evt);
            }
        });

        ButtonSquareRoot.setBackground(new java.awt.Color(153, 153, 153));
        ButtonSquareRoot.setText("√");
        ButtonSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSquareRootActionPerformed(evt);
            }
        });

        ButtonCubeRoot.setBackground(new java.awt.Color(153, 153, 153));
        ButtonCubeRoot.setText("³√ ");
        ButtonCubeRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCubeRootActionPerformed(evt);
            }
        });

        ButtonFactorial.setBackground(new java.awt.Color(153, 153, 153));
        ButtonFactorial.setText("x!");
        ButtonFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFactorialActionPerformed(evt);
            }
        });

        ButtonOff.setBackground(new java.awt.Color(255, 0, 0));
        ButtonOff.setForeground(new java.awt.Color(255, 255, 255));
        ButtonOff.setText("OFF");
        ButtonOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOffActionPerformed(evt);
            }
        });

        ButtonDivide.setBackground(new java.awt.Color(0, 0, 0));
        ButtonDivide.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDivide.setText("÷");
        ButtonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDivideActionPerformed(evt);
            }
        });

        Button9.setBackground(new java.awt.Color(0, 0, 0));
        Button9.setForeground(new java.awt.Color(255, 255, 255));
        Button9.setText("9");
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });

        Button8.setBackground(new java.awt.Color(0, 0, 0));
        Button8.setForeground(new java.awt.Color(255, 255, 255));
        Button8.setText("8");
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });

        Button7.setBackground(new java.awt.Color(0, 0, 0));
        Button7.setForeground(new java.awt.Color(255, 255, 255));
        Button7.setText("7");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });

        ButtoneEulerNumber.setBackground(new java.awt.Color(153, 153, 153));
        ButtoneEulerNumber.setText("e");
        ButtoneEulerNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtoneEulerNumberActionPerformed(evt);
            }
        });

        ButtonSin.setBackground(new java.awt.Color(153, 153, 153));
        ButtonSin.setText("sin");
        ButtonSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSinActionPerformed(evt);
            }
        });

        ButtonInverse.setBackground(new java.awt.Color(0, 0, 51));
        ButtonInverse.setForeground(new java.awt.Color(255, 255, 255));
        ButtonInverse.setText("Inverse");
        ButtonInverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInverseActionPerformed(evt);
            }
        });

        ButtonPI.setBackground(new java.awt.Color(153, 153, 153));
        ButtonPI.setText("π");
        ButtonPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPIActionPerformed(evt);
            }
        });

        Button5.setBackground(new java.awt.Color(0, 0, 0));
        Button5.setForeground(new java.awt.Color(255, 255, 255));
        Button5.setText("5");
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });

        Button4.setBackground(new java.awt.Color(0, 0, 0));
        Button4.setForeground(new java.awt.Color(255, 255, 255));
        Button4.setText("4");
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });

        ButtonMultiply.setBackground(new java.awt.Color(0, 0, 0));
        ButtonMultiply.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMultiply.setText("×");
        ButtonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMultiplyActionPerformed(evt);
            }
        });

        Button6.setBackground(new java.awt.Color(0, 0, 0));
        Button6.setForeground(new java.awt.Color(255, 255, 255));
        Button6.setText("6");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });

        ButtonLog.setBackground(new java.awt.Color(153, 153, 153));
        ButtonLog.setText("log");
        ButtonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogActionPerformed(evt);
            }
        });

        ButtonCos.setBackground(new java.awt.Color(153, 153, 153));
        ButtonCos.setText("cos");
        ButtonCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCosActionPerformed(evt);
            }
        });

        ButtonAntilog.setBackground(new java.awt.Color(153, 153, 153));
        ButtonAntilog.setText("ln");
        ButtonAntilog.setToolTipText("ANS");
        ButtonAntilog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAntilogActionPerformed(evt);
            }
        });

        Button1.setBackground(new java.awt.Color(0, 0, 0));
        Button1.setForeground(new java.awt.Color(255, 255, 255));
        Button1.setText("1");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        Button3.setBackground(new java.awt.Color(0, 0, 0));
        Button3.setForeground(new java.awt.Color(255, 255, 255));
        Button3.setText("3");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });

        ButtonTan.setBackground(new java.awt.Color(153, 153, 153));
        ButtonTan.setText("tan");
        ButtonTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTanActionPerformed(evt);
            }
        });

        ButtonSquare.setBackground(new java.awt.Color(153, 153, 153));
        ButtonSquare.setText("x²");
        ButtonSquare.setToolTipText("");
        ButtonSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSquareActionPerformed(evt);
            }
        });

        Button2.setBackground(new java.awt.Color(0, 0, 0));
        Button2.setForeground(new java.awt.Color(255, 255, 255));
        Button2.setText("2");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });

        ButtonMinus.setBackground(new java.awt.Color(0, 0, 0));
        ButtonMinus.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMinus.setText("-");
        ButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMinusActionPerformed(evt);
            }
        });

        Button10powerX.setBackground(new java.awt.Color(153, 153, 153));
        Button10powerX.setText("*10^x");
        Button10powerX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button10powerXActionPerformed(evt);
            }
        });

        ButtonPower.setBackground(new java.awt.Color(153, 153, 153));
        ButtonPower.setText("x^");
        ButtonPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPowerActionPerformed(evt);
            }
        });

        ButtonPlus.setBackground(new java.awt.Color(0, 0, 0));
        ButtonPlus.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPlus.setText("+");
        ButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPlusActionPerformed(evt);
            }
        });

        Button0.setBackground(new java.awt.Color(0, 0, 0));
        Button0.setForeground(new java.awt.Color(255, 255, 255));
        Button0.setText("0");
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });

        ButtonEqualsTo.setBackground(new java.awt.Color(0, 0, 0));
        ButtonEqualsTo.setForeground(new java.awt.Color(255, 255, 255));
        ButtonEqualsTo.setText("=");
        ButtonEqualsTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEqualsToActionPerformed(evt);
            }
        });

        ButtonBackSpace.setBackground(new java.awt.Color(255, 0, 0));
        ButtonBackSpace.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBackSpace.setText("←");
        ButtonBackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackSpaceActionPerformed(evt);
            }
        });

        ButtonPoint.setBackground(new java.awt.Color(0, 0, 0));
        ButtonPoint.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPoint.setText(".");
        ButtonPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPointActionPerformed(evt);
            }
        });

        RadioButtonON.setText("ON");
        RadioButtonON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonONActionPerformed(evt);
            }
        });

        RadioButtonOFF.setForeground(new java.awt.Color(255, 255, 255));
        RadioButtonOFF.setText("OFF");
        RadioButtonOFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonOFFActionPerformed(evt);
            }
        });

        Label.setForeground(new java.awt.Color(0, 51, 255));
        Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Label.setText("BIPIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonOff, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonCubeRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonAllClear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonInverse, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonSin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtoneEulerNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonLog, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonCos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonPI, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonAntilog, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonTan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonOneByX, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonPower, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button10powerX, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonEqualsTo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RadioButtonON, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioButtonOFF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DisplayText, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioButtonON, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RadioButtonOFF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Label)
                        .addGap(2, 2, 2)))
                .addComponent(DisplayText, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAllClear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCubeRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonOff, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtoneEulerNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonInverse, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPI, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonLog, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonTan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAntilog, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonEqualsTo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button10powerX, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPower, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonOneByX, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu3.setText("View");

        jMenuItem1.setText("Plain");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("About");

        jMenuItem2.setText("Me");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplayTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayTextActionPerformed

    private void ButtonAllClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAllClearActionPerformed
        DisplayText.setText("");
        Label.setText("");
    }//GEN-LAST:event_ButtonAllClearActionPerformed

    private void ButtonPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPercentageActionPerformed
        num1 = Double.parseDouble(DisplayText.getText());
        DisplayText.setText("");
        operator = "%";
        Label.setText(num1 +"%");
    }//GEN-LAST:event_ButtonPercentageActionPerformed

    private void ButtonOneByXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOneByXActionPerformed
        num1 = Double.parseDouble(DisplayText.getText());
        result = 1/num1;
        DisplayText.setText(String.valueOf(result));
    }//GEN-LAST:event_ButtonOneByXActionPerformed

    private void ButtonSquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSquareRootActionPerformed
       num1 = Double.parseDouble(DisplayText.getText());
       double sqrt = Math.sqrt(num1);
       DisplayText.setText(String.valueOf(sqrt));
    }//GEN-LAST:event_ButtonSquareRootActionPerformed

    private void ButtonCubeRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCubeRootActionPerformed
        num1 = Double.parseDouble(DisplayText.getText());
        double cbrt = Math.cbrt(num1);
        DisplayText.setText(String.valueOf(cbrt));
    }//GEN-LAST:event_ButtonCubeRootActionPerformed

    private void ButtonFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFactorialActionPerformed
        num1 = Integer.parseInt(DisplayText.getText());
        int fact = 1;
        for(int i=1;i<=num1;i++) {
            fact= fact * i;
        }
        DisplayText.setText(String.valueOf(fact));
    }//GEN-LAST:event_ButtonFactorialActionPerformed

    private void ButtonOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOffActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ButtonOffActionPerformed

    private void ButtonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDivideActionPerformed
        num1 = Double.parseDouble(DisplayText.getText());
        DisplayText.setText("");
        operator = "/";
        Label.setText(num1 +"÷");
    }//GEN-LAST:event_ButtonDivideActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        DisplayText.setText(DisplayText.getText() +"9");
    }//GEN-LAST:event_Button9ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        DisplayText.setText(DisplayText.getText() +"8");
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        DisplayText.setText(DisplayText.getText() +"7");
    }//GEN-LAST:event_Button7ActionPerformed

    private void ButtoneEulerNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtoneEulerNumberActionPerformed
        num1 = Double.parseDouble(DisplayText.getText());
        DisplayText.setText(String.valueOf(Math.exp(num1)));
    }//GEN-LAST:event_ButtoneEulerNumberActionPerformed

    private void ButtonSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSinActionPerformed
        num1 = Double.parseDouble(DisplayText.getText());
        double radians = Math.toRadians(num1);
        result = Math.sin(radians);
        DisplayText.setText(String.valueOf(result));
    }//GEN-LAST:event_ButtonSinActionPerformed

    private void ButtonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogActionPerformed
        num1 = Double.parseDouble(DisplayText.getText());
        DisplayText.setText(String.valueOf(Math.log(num1) / 2.302585093 ));
    }//GEN-LAST:event_ButtonLogActionPerformed

    private void ButtonCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCosActionPerformed
        num1 = Double.parseDouble(DisplayText.getText());
        double radians = Math.toRadians(num1);
        DisplayText.setText(String.valueOf(Math.cos(radians)));
    }//GEN-LAST:event_ButtonCosActionPerformed

    private void ButtonPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPIActionPerformed
        DisplayText.setText(String.valueOf(Math.PI));       
    }//GEN-LAST:event_ButtonPIActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        DisplayText.setText(DisplayText.getText() +"4");
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
       DisplayText.setText(DisplayText.getText() +"5");
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        DisplayText.setText(DisplayText.getText() +"6");
    }//GEN-LAST:event_Button6ActionPerformed

    private void ButtonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMultiplyActionPerformed
        num1 = Double.parseDouble(DisplayText.getText());
        DisplayText.setText("");
        operator = "*";
        Label.setText(num1 +"x");
    }//GEN-LAST:event_ButtonMultiplyActionPerformed

    private void ButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMinusActionPerformed
        num1 = Double.parseDouble(DisplayText.getText());
        DisplayText.setText("");
        operator = "-";
    }//GEN-LAST:event_ButtonMinusActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        DisplayText.setText(DisplayText.getText() +"3");
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        DisplayText.setText(DisplayText.getText() +"2");
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
       DisplayText.setText(DisplayText.getText() +"1");
    }//GEN-LAST:event_Button1ActionPerformed

    private void ButtonSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSquareActionPerformed
        num1 = Double.parseDouble(DisplayText.getText());
        result = Math.pow(num1,2);
        DisplayText.setText(String.valueOf(result));
    }//GEN-LAST:event_ButtonSquareActionPerformed

    private void ButtonTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTanActionPerformed
        num1 = Double.parseDouble(DisplayText.getText());
        double radians = Math.toRadians(num1);
        DisplayText.setText(String.valueOf(Math.tan(radians)));
    }//GEN-LAST:event_ButtonTanActionPerformed

    private void ButtonAntilogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAntilogActionPerformed
        num1 = Double.parseDouble(DisplayText.getText());
        DisplayText.setText(String.valueOf(Math.log(num1)));
    }//GEN-LAST:event_ButtonAntilogActionPerformed

    private void ButtonBackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackSpaceActionPerformed
       int length = DisplayText.getText().length();
       int number = DisplayText.getText().length() - 1;
       if(length>0) {
           StringBuilder back = new StringBuilder(DisplayText.getText());
           back.deleteCharAt(number);
           DisplayText.setText(String.valueOf(back));
           
       }
    }//GEN-LAST:event_ButtonBackSpaceActionPerformed

    private void ButtonPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPowerActionPerformed
        num1 = Double.parseDouble(DisplayText.getText());
        DisplayText.setText("");
        operator = "^";
    }//GEN-LAST:event_ButtonPowerActionPerformed

    private void Button10powerXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button10powerXActionPerformed
        num1 = Double.parseDouble(DisplayText.getText());
        DisplayText.setText("");
        operator = "x10";
        Label.setText(num1 +"x10^");
    }//GEN-LAST:event_Button10powerXActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
        DisplayText.setText(DisplayText.getText() +"0");
    }//GEN-LAST:event_Button0ActionPerformed

    private void ButtonPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPointActionPerformed
        String enterValue = DisplayText.getText() + ButtonPoint.getText();
        DisplayText.setText(enterValue);
    }//GEN-LAST:event_ButtonPointActionPerformed

    private void ButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPlusActionPerformed
       num1 = Double.parseDouble(DisplayText.getText());
       DisplayText.setText("");
       operator = "+";
       Label.setText(num1 +"+");
    }//GEN-LAST:event_ButtonPlusActionPerformed

    private void ButtonEqualsToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEqualsToActionPerformed
        num2 = Double.parseDouble(DisplayText.getText());
        switch(operator) {
        case "+":
            result = num1 + num2;
            DisplayText.setText(String.valueOf(result));
            break;
            
        case "-":
            result = num1 - num2;
            DisplayText.setText(String.valueOf(result));
            break;
            
        case "*":
            result = num1 * num2;
            DisplayText.setText(String.valueOf(result));
            break;
            
        case "/":
            result = num1 / num2;
            DisplayText.setText(String.valueOf(result));
            break;
            
        case "%":
            result = num1 * (num2/100);
            DisplayText.setText(String.valueOf(result));
            break;
            
        case "^":
            result = Math.pow(num1, num2);
            DisplayText.setText(String.valueOf(result));
            break;
            
        case "x10":
            result = (num1 * Math.pow(10,num2));
            DisplayText.setText(String.valueOf(result));
            break;
        }
        
        Label.setText("");
    }//GEN-LAST:event_ButtonEqualsToActionPerformed

    private void ButtonInverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInverseActionPerformed
        this.dispose();
        new CalculatorView2nd().setVisible(true);
    }//GEN-LAST:event_ButtonInverseActionPerformed

    private void RadioButtonONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonONActionPerformed
        RadioButtonOFF.setEnabled(true);
        RadioButtonON.setEnabled(false);
        
        DisplayText.setEnabled(true);
        Button1.setEnabled(true);
        Button2.setEnabled(true);
        Button3.setEnabled(true);
        Button4.setEnabled(true);
        Button5.setEnabled(true);
        Button6.setEnabled(true);
        Button7.setEnabled(true);
        Button8.setEnabled(true);
        Button9.setEnabled(true);
        Button0.setEnabled(true);
        ButtonPoint.setEnabled(true);
        ButtonAllClear.setEnabled(true);
        ButtonBackSpace.setEnabled(true);
        ButtonPercentage.setEnabled(true);
        ButtonSquareRoot.setEnabled(true);
        ButtonCubeRoot.setEnabled(true);
        ButtonFactorial.setEnabled(true);
        ButtonOff.setEnabled(true);
        ButtonInverse.setEnabled(true);
        ButtonSin.setEnabled(true);
        ButtonCos.setEnabled(true);
        ButtonTan.setEnabled(true);
        ButtoneEulerNumber.setEnabled(true);
        ButtonPlus.setEnabled(true);
        ButtonMinus.setEnabled(true);
        ButtonMultiply.setEnabled(true);
        ButtonDivide.setEnabled(true);
        ButtonEqualsTo.setEnabled(true);
        ButtonLog.setEnabled(true);
        ButtonAntilog.setEnabled(true);
        ButtonPI.setEnabled(true);
        ButtonSquare.setEnabled(true);
        Button10powerX.setEnabled(true);
        ButtonPower.setEnabled(true);
        ButtonOneByX.setEnabled(true); 
        
        DisplayText.setText("");
        Label.setText("");
        
    }//GEN-LAST:event_RadioButtonONActionPerformed

    private void RadioButtonOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonOFFActionPerformed
        RadioButtonON.setEnabled(true);
        RadioButtonOFF.setEnabled(false);
                
        DisplayText.setEnabled(false);
        Button1.setEnabled(false);
        Button2.setEnabled(false);
        Button3.setEnabled(false);
        Button4.setEnabled(false);
        Button5.setEnabled(false);
        Button6.setEnabled(false);
        Button7.setEnabled(false);
        Button8.setEnabled(false);
        Button9.setEnabled(false);
        Button0.setEnabled(false);
        ButtonPoint.setEnabled(false);
        ButtonAllClear.setEnabled(false);
        ButtonBackSpace.setEnabled(false);
        ButtonPercentage.setEnabled(false);
        ButtonSquareRoot.setEnabled(false);
        ButtonCubeRoot.setEnabled(false);
        ButtonFactorial.setEnabled(false);
        ButtonOff.setEnabled(false);
        ButtonInverse.setEnabled(false);
        ButtonSin.setEnabled(false);
        ButtonCos.setEnabled(false);
        ButtonTan.setEnabled(false);
        ButtoneEulerNumber.setEnabled(false);
        ButtonPlus.setEnabled(false);
        ButtonMinus.setEnabled(false);
        ButtonMultiply.setEnabled(false);
        ButtonDivide.setEnabled(false);
        ButtonEqualsTo.setEnabled(false);
        ButtonLog.setEnabled(false);
        ButtonAntilog.setEnabled(false);
        ButtonPI.setEnabled(false);
        ButtonSquare.setEnabled(false);
        Button10powerX.setEnabled(false);
        ButtonPower.setEnabled(false);
        ButtonOneByX.setEnabled(false);
        
        DisplayText.setText("");
        Label.setText("");
    }//GEN-LAST:event_RadioButtonOFFActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        new Calculator().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(null,"Bipin Shrestha Production:Advance Calculator \n"
                + "Product Version: 1.0.13 \n Please Visit: sthabipin.com.np","About",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button10powerX;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonAllClear;
    private javax.swing.JButton ButtonAntilog;
    private javax.swing.JButton ButtonBackSpace;
    private javax.swing.JButton ButtonCos;
    private javax.swing.JButton ButtonCubeRoot;
    private javax.swing.JButton ButtonDivide;
    private javax.swing.JButton ButtonEqualsTo;
    private javax.swing.JButton ButtonFactorial;
    private javax.swing.JButton ButtonInverse;
    private javax.swing.JButton ButtonLog;
    private javax.swing.JButton ButtonMinus;
    private javax.swing.JButton ButtonMultiply;
    private javax.swing.JButton ButtonOff;
    private javax.swing.JButton ButtonOneByX;
    private javax.swing.JButton ButtonPI;
    private javax.swing.JButton ButtonPercentage;
    private javax.swing.JButton ButtonPlus;
    private javax.swing.JButton ButtonPoint;
    private javax.swing.JButton ButtonPower;
    private javax.swing.JButton ButtonSin;
    private javax.swing.JButton ButtonSquare;
    private javax.swing.JButton ButtonSquareRoot;
    private javax.swing.JButton ButtonTan;
    private javax.swing.JButton ButtoneEulerNumber;
    private javax.swing.JTextField DisplayText;
    private javax.swing.JLabel Label;
    private javax.swing.JRadioButton RadioButtonOFF;
    private javax.swing.JRadioButton RadioButtonON;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
